# # Docker
# # Build a Docker image
# # https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# trigger:
# - main

# resources:
# - repo: self

# # variables:
# #   tag: '$(Build.BuildId)'

# stages:
# - stage: Build
#   displayName: Build image
#   jobs:
#   - job: Build
#     displayName: Build
#     pool:
#       vmImage: ubuntu-latest
#     steps:
#     - task: Docker@2
#       displayName: Build an image
#       inputs:
#         containerRegistry: 'Azure-devops-docker-hub'
#         command: 'login'
#     - task: trivy@1
#       inputs:
#         version: 'latest'
#         debug: true
#         image: 'sivakalahasthy/azuredevops'
#         exitCode: '0'

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Scanthelocalproject
    steps:
    - task: trivy@1
      inputs:
        version: 'latest'
        path: '.'
        exitCode: '0'
  - job: Scantheubuntuimage
    steps:
    - task: trivy@1
      inputs:
        version: 'latest'
        image: 'ubuntu'
        exitCode: '0'