trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Scanthelocalproject
    steps:
    - task: trivy@1
      inputs:
        version: 'latest'
        path: '.'
        exitCode: '0'
  - job: Scantheubuntuimage
    steps:
    - task: trivy@1
      inputs:
        version: 'latest'
        image: 'ubuntu'
        exitCode: '0'